services:
  db:
    image: postgres:16
    container_name: jobsy_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobsy
    ports:
      - "5432:5432"
    volumes:
      - jobsy_pg:/var/lib/postgresql/data

volumes:
  jobsy_pg:
